# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b047b71aa4ae59025eacd176242afc866f6bb988d59c1f1d0d20ec66ccbcbd771e27eea97545cba7d0d2348fdd29b849809784c31997b8ab3a4e902f9f5a5cb

test:
  secret_key_base: f6a9e2ad56a29db781410421821c3cb82aaba1452dcc03cb1481240268a69d87d2a95308de9cc48e42009f18ab05264ecfc4b6b7fd8bbf6a9f4cbff01493f967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
